name: adatamu_app
description: "Aplikasi Buku Tamu Digital AdaTamu"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  http: ^1.2.2
  image_picker: ^1.1.2
  camera: ^0.11.0+2
  camera_windows: ^0.2.5
  image: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true